### ISSUE TITLE
Reusing extracted data from previous step

### ISSUE THREAD

**Issue by umpirsky** [blackfireio/player#28]
Scenario like this works as expected:

```yaml
scenario:
    steps:
        - visit: url('http://example.com')
          extract:
             hrefs: css("a").extract("href")
        - visit: url(hrefs[0])
          extract:
              title: css("title")
```

Would be nice if it can iterate over results from previous step:

```yaml
scenario:
    steps:
        - visit: url('http://example.com')
          extract:
             hrefs: css("a").extract("href")
        - visit: url(hrefs)
          extract:
              title: css("title")
```

This gives: `PHP Warning:  ltrim() expects parameter 1 to be string, array given in phar:///usr/local/bin/blackfire-player.phar/Player/Guzzle/RequestFactory.php on line 60`. Is there any workaround?
